version: 2.1

orbs:
  rust: circleci/rust@1.6.0
  browser-tools: circleci/browser-tools@1.2.4

workflows:
  full_test_suite:  # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - models_and_api
      - integration_tests
      - back_office_panel_tests

jobs:
  integration_tests:
    docker:
      - image: constata/test:latest
      - image: cimg/postgres:13.4
        environment:
          POSTGRES_USER: constata
          POSTGRES_PASSWORD: password
          POSTGRES_DB: constata_development
    resource_class: xlarge
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Creating config
          command: cp Rocket.toml.example Rocket.toml
      - run:
          name: Wait for postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for schema creation
          command: cd constata_lib/db && until sqlx database setup; do echo "Creating DB"; sleep 1; done;
      - run:
          name: Make artifacts dir
          command: mkdir -p target/artifacts

      - run:
          name: Building libs for dev
          command: cargo build --workspace --lib

      - run:
          name: Building public api server
          command: cargo build --release -p public_api

      - run:
          name: Run tests
          command: cargo test -p integration_tests --no-fail-fast -- --skip back_office_panel --test-threads 1

      - store_artifacts:
          path: target/artifacts

  back_office_panel_tests:
    docker:
      - image: constata/test:latest
      - image: cimg/postgres:13.4
        environment:
          POSTGRES_USER: constata
          POSTGRES_PASSWORD: password
          POSTGRES_DB: constata_development
    resource_class: xlarge
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Creating config
          command: cp Rocket.toml.example Rocket.toml

      - run:
          name: Wait for postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for schema creation
          command: cd constata_lib/db && until sqlx database setup; do echo "Creating DB"; sleep 1; done;
      - run:
          name: Make artifacts dir
          command: mkdir -p target/artifacts

      - run:
          name: Building libs for dev
          command: cargo build --workspace --lib

      - run:
          name: Run back office tests
          command: cargo test -p integration_tests back_office_panel --no-fail-fast -- --test-threads 1

      - store_artifacts:
          path: target/artifacts

  models_and_api:
    docker:
      - image: constata/test:latest
      - image: cimg/postgres:13.4
        environment:
          POSTGRES_USER: constata
          POSTGRES_PASSWORD: password
          POSTGRES_DB: constata_development
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Creating config
          command: cp Rocket.toml.example Rocket.toml
      - run:
          name: Wait for postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for schema creation
          command: cd constata_lib/db && until sqlx database setup; do echo "Creating DB"; sleep 1; done;
      - run:
          name: Make artifacts dir
          command: mkdir -p target/artifacts

      - run:
          name: Run tests
          command: cargo test --workspace --exclude email_bot --exclude integration_tests --no-fail-fast -- --test-threads 1

      - store_artifacts:
          path: target/artifacts
